### ISSUE TITLE
Questions about caffe converter

### ISSUE THREAD

**Issue by LittleDonkey1203** [Charrin/RetinaFace-Cpp#10]
I use this repo: https://github.com/cypw/MXNet2Caffe to convert caffe model from mxnet. 
But I found the BN op gives a big error like max bias = 0.##, Have you got some ideas to solve this problem?

**Comment by LittleDonkey1203** [comment]
Sorry, maybe not BN, but our converted model totally perform different values. I'm not sure where are the error comes from.

**Comment by Charrin** [comment]
Maybe you should print intermediate blobs to find out ops that cause the difference

**Comment by LittleDonkey1203** [comment]
Ok, I solved it, it’s caused by very little difference between BN on params of moving average and eps.

**Comment by fengxueem** [comment]
Hi, LittleDonkey1203 and Charrin
Good to hear that you guys have successfully converted the model from MXNet to Caffe, would you please consider opensourcing the converter or the converted caffemodel(For now, ncnn version of mobilenet-retinaface and caffe version mnet-retinaface are provided by Charrin)? It'll be so helpful  to have the converted caffemodel that we could try retinaface on MNN and other inference framework. 
Thanks in advance.

**Comment by Charrin** [comment]
> Hi, LittleDonkey1203 and Charrin
> Good to hear that you guys have successfully converted the model from MXNet to Caffe, would you please consider opensourcing the converter or the converted caffemodel(For now, ncnn version of mobilenet-retinaface and caffe version of mnet-retinaface & R50-retinaface are provided by Charrin)? It'll be so helpful to have the converted caffemodel that we could try retinaface on MNN and other inference framework.
> Thanks in advance.

@fengxueem I release converted Caffe models, please see README

**Comment by fengxueem** [comment]
@Charrin 
Thank you for replying this quick. Yes, I found that caffemodels are released. And I am studying this model now. Thanks again. It will be better if you could kindly share the code of converter, :)
And, there might be a small typo in R50.prototxt(downloaded from Baidu cloud) at line 2722 & 2723. Stride and kernel_size are defined twice there. From my understanding to the caffe framework, only the 1st definition works(stride=2,kernel_size=4). Besides, this deconv layer actually works as an nearest upsampling layer, in terms of inference speed, maybe converting it to an interp layer defined in PSPNet is a better choice for mobile inference framework like ncnn.
Anyway, thanks for your work.

**Comment by Charrin** [comment]
> @Charrin
> Thank you for replying this quick. Yes, I found that caffemodels are released. And I am studying this model now. Thanks again. It will be better if you could kindly share the code of converter, :)
> And, there might be a small typo in R50.prototxt(downloaded from Baidu cloud) at line 2722 & 2723. Stride and kernel_size are defined twice there. From my understanding to the caffe framework, only the 1st definition works(stride=2,kernel_size=4). Besides, this deconv layer actually works as an nearest upsampling layer, in terms of inference speed, maybe converting it to an interp layer defined in PSPNet is a better choice for mobile inference framework like ncnn.
> Anyway, thanks for your work.

@fengxueem Sorry, The multiple definitions of stride and kernel_size is my mistake, I forgot to delete them. Thank you!
I use MMDNN and modify some code, it is not useful to release the code because it just finishes the converting process without mistake, I should modify the output prototxt file to make the results correct.

**Comment by fengxueem** [comment]
@Charrin Gotcha,:)

**Comment by EEWenbinWu** [comment]
> Ok, I solved it, it’s caused by very little difference between BN on params of moving average and eps.

Hi, I got some problem when converting my own mxnet model to caffe，I guess that is because of the BN layer, could you please tell me how you deal with your problem?
