### ISSUE TITLE
Is the output same?

### ISSUE THREAD

**Issue by zhangjinhong17** [Charrin/RetinaFace-Cpp#11]
Hi,
    Thanks for your good job.
    I tried your retinaface-R50 caffe model, the output size is not same as the MXNET output.
    For example, the stride 8 output size, if the input size is 640x640, the caffe model output size is 81x81, but MXNET output size is 80x80
    
    Is it same as your caffe model output?

Thanks
Jinhong

**Comment by Charrin** [comment]
> Hi,
> Thanks for your good job.
> I tried your retinaface-R50 caffe model, the output size is not same as the MXNET output.
> For example, the stride 8 output size, if the input size is 640x640, the caffe model output size is 81x81, but MXNET output size is 80x80
> 
> ```
> Is it same as your caffe model output?
> ```
> 
> Thanks
> Jinhong

@zhangjinhong17 my output is 80x80

>>> net=caffe.Net('mnet.prototxt', 'mnet.caffemodel', caffe.TEST)
W0604 11:15:11.890946 25723 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0604 11:15:11.890981 25723 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0604 11:15:11.890997 25723 _caffe.cpp:142] Net('mnet.prototxt', 1, weights='mnet.caffemodel')
>>> out=net.forward()
>>> out['face_rpn_cls_prob_reshape_stride8'].data.shape
(1, 4, 80, 80)

**Comment by zhangjinhong17** [comment]
@Charrin ,
    Thanks for your double confirm.
    Yes, I checked the mnet.prototxt, the output is exactly [1,4,80,80]
    But, the R50.prototxt, the output is [1,4,81,81], I think it is not same as the official retinaface-R50 output.

import caffe

net=caffe.Net('./retinaface_r50_caffe/R50.prototxt', './retinaface_r50_caffe/R50.caffemodel', caffe.TEST)
out=net.forward()
print(out['face_rpn_cls_prob_reshape_stride8'].data.shape)

The result is:
(1, 4, 65, 65)

Thanks
Jinhong

**Comment by Charrin** [comment]
> @Charrin ,
> Thanks for your double confirm.
> Yes, I checked the mnet.prototxt, the output is exactly [1,4,80,80]
> But, the R50.prototxt, the output is [1,4,81,81], I think it is not same as the official retinaface-R50 output.
> 
> import caffe
> 
> net=caffe.Net('./retinaface_r50_caffe/R50.prototxt', './retinaface_r50_caffe/R50.caffemodel', caffe.TEST)
> out=net.forward()
> print(out['face_rpn_cls_prob_reshape_stride8'].data.shape)
> 
> the input size is 600x600
> The result is:
> (1, 4, 76, 76)
> 
> I think the right size should be 600/8=75
> 
> Thanks
> Jinhong

@zhangjinhong17 I think it is because the output pooling size calculating difference between Caffe and MXNet

In caffe, you can see:
  
> pooled_height_ = static_cast<int>(ceil(static_cast<float>(
>       height_ + 2 * pad_h_ - kernel_h_) / stride_h_)) + 1;
> pooled_width_ = static_cast<int>(ceil(static_cast<float>(
>      width_ + 2 * pad_w_ - kernel_w_) / stride_w_)) + 1;

in Pooling0, kernel_size = 3, stride = 2, pad = 1, input is 300x300
so output is ceil((300+2*1-3)/2)+1 = ceil(149.5)+1 = 151
but in mxneet the output is 150
