### ISSUE TITLE
Widerface valuation

### ISSUE THREAD

**Issue by zhly0** [Charrin/RetinaFace-Cpp#12]
Hi，Charrin：
    what format should I save the widerface test result in order to test the widerface val dataset，I could not find a doc that explain it.Thanks.

**Comment by Charrin** [comment]
widerface provides evaluation tool, use it you will get .mat file, use pascal voc evaluate and get final result

**Comment by zhly0** [comment]
@Charrin ，Thanks for quick reply，I know the tool，which need to save the prediction result as .mat file，and I do not know what attribute the saved .mat file should have.

**Comment by Charrin** [comment]
> @Charrin ，Thanks for quick reply，I know the tool，which need to save the prediction result as .mat file，and I do not know what attribute the saved .mat file should have.

@zhly0 please see https://github.com/Charrin/RetinaFace-Cpp/tree/master/results/mnet/cpp_detect as an example.
The prediction results are saved as a .txt file, each .jpg corresponds a .txt file, .mat files are the curves

**Comment by zhly0** [comment]
@Charrin ，Thanks！
