### ISSUE TITLE
Different size for input image

### ISSUE THREAD

**Issue by github-luffy** [Charrin/RetinaFace-Cpp#15]
when i modify the size of input image to 640 * 640, got no result for stride8, but got the result for stride16 and stride32. but I don't know why.

**Comment by Charrin** [comment]
What’s your original image ratio? I think you should keep the input ratio as same as the original image ratio.

**Comment by github-luffy** [comment]
original image is 640*480，and I also use 640*480 for input image,got no result for stride8, but got the result for stride16 and stride32.

**Comment by Charrin** [comment]
> original image is 640_480，and I also use 640_480 for input image,got no result for stride8, but got the result for stride16 and stride32.

@github-luffy It depends on the faces size, too.

**Comment by github-luffy** [comment]
@Charrin  Maybe I didn't say correctly, That I got no result for stride8 means code got something wrong. such as code(cv::imshow("img", img)) doesn't work.

**Comment by Charrin** [comment]
> @Charrin Maybe I didn't say correctly, That I got no result for stride8 means code got something wrong. such as code(cv::imshow("img", img)) doesn't work.

@github-luffy can you provide the test image?

**Comment by Charrin** [comment]
> > @Charrin Maybe I didn't say correctly, That I got no result for stride8 means code got something wrong. such as code(cv::imshow("img", img)) doesn't work.
> 
> @github-luffy can you provide the test image?

@github-luffy Does your test image work well through original retinaface code?

**Comment by github-luffy** [comment]
300*300 is ok, 640*480 and 640*640 make code(cv::imshow("img", img)) doesn't work，no result. I run camera(640*480).

**Comment by Charrin** [comment]
> 300_300 is ok, 640_480 and 640_640 make code(cv::imshow("img", img)) doesn't work，no result. I run camera(640_480).

@github-luffy 不好意思 没理解你的问题是什么，是stride=8没输出人脸结果？我也不清楚你的测试图片和方式是什么，方便的话可以加qq描述一下

**Comment by github-luffy** [comment]
输入图片为640*480， resize为640*480，结果跑不起来。但输入图片为640*480， resize为640*320，结果可以跑起来。

**Comment by github-luffy** [comment]
stride = 32:
cls 4 15 20
reg 8 15 20
pts 20 15 20
stride = 16:
cls 4 30 40
reg 8 30 40
pts 20 30 40，stride=8没有结果，且代码一直卡在这里。

**Comment by Charrin** [comment]
所以是卡在 FilterAnchor 里面了吗？o-o
挺奇怪的 FilterAnchor里你能打印输出的feature map 大小吗

**Comment by github-luffy** [comment]
_extractor.extract(clsname, cls);
_extractor.extract(regname, reg);
_extractor.extract(ptsname, pts);
上面代码之后的代码都不能打印东西了

**Comment by Charrin** [comment]
_extractor.extract(clsname, cls);
_extractor.extract(regname, reg);
_extractor.extract(ptsname, pts);

**Comment by Charrin** [comment]
_extractor.extract(clsname, cls);
printf("cls done\n");
_extractor.extract(regname, reg);
printf("reg done\n");
_extractor.extract(ptsname, pts);
printf("pts done\n");

ac[i].FilterAnchor(&cls, &reg, &pts, proposals);
printf("filter done\n")

pts done 这个log可以输出， filter done输出不了了对吗

**Comment by github-luffy** [comment]
你描写的printf都输出不了

**Comment by Charrin** [comment]
那可能卡在了_extractor.extract(clsname, cls); 这一步
跟推理框架相关的具体原因就不是很清楚了
你可以尝试用GDB跟踪调试一下

**Comment by github-luffy** [comment]
_extractor.extract(clsname, cls);我调试了一会，跳转此函数，直接显示越界操作。
0x00007FF6A5DE2240 处(位于 src.exe 中)引发的异常: 0xC0000005: 读取位置 0x000001C40595F000 时发生访问冲突。
如有适用于此异常的处理程序，该程序便可安全地继续运行。
