### ISSUE TITLE
mxnet model convert to ncnn

### ISSUE THREAD

**Issue by HansonSun** [Charrin/RetinaFace-Cpp#16]
您好,
    请问你的ncnn模型是用的  mnet.25-symbol.json    mnet.25-0000.params 这两个文件转的吗, 
我用ncnn最新代码转,运行会报错.查看了一下转换后的ncnn模型和你工程中的差别蛮大的, 你转换的时候用了什么技巧吗,你ncnn的tag 是多少

谢谢

**Comment by Charrin** [comment]
> 您好,
> 请问你的ncnn模型是用的 mnet.25-symbol.json mnet.25-0000.params 这两个文件转的吗,
> 我用ncnn最新代码转,运行会报错.查看了一下转换后的ncnn模型和你工程中的差别蛮大的, 你转换的时候用了什么技巧吗,你ncnn的tag 是多少
> 
> 谢谢

@HansonSun 用我提供的caffe模型转

**Comment by HansonSun** [comment]
您好
 ,
请问下您使用mmdnn  mxnet转caffe 有做什么修改,可以指点一下吗.

谢谢

**Comment by Charrin** [comment]
> 您好
> ,
> 请问下您使用mmdnn mxnet转caffe 有做什么修改,可以指点一下吗.
> 
> 谢谢

把缺失的op手动添加就好了

**Comment by Charrin** [comment]
> > 您好
> > ,
> > 请问下您使用mmdnn mxnet转caffe 有做什么修改,可以指点一下吗.
> > 谢谢
> 
> 把缺失的op手动添加就好了

具体参考里面其他op解析的实现

**Comment by HansonSun** [comment]
你说的改op是把那些 null改成正确的名字吗,如果是的话需要改成什么. 参考op解析是研究mmdnn里面解析op的代码吗.
大佬你是主页里面qq群的群主吗.

Thanks

**Comment by Charrin** [comment]
> 你说的改op是把那些 null改成正确的名字吗,如果是的话需要改成什么. 参考op解析是研究mmdnn里面解析op的代码吗.
> 大佬你是主页里面qq群的群主吗.
> 
> Thanks

对应op要实现一下，比如你加了crop，对应解析到caffe时候也要加crop
