### ISSUE TITLE
可以提供一下caffe版本的预测sample代码吗？

### ISSUE THREAD

**Issue by yhl41001** [Charrin/RetinaFace-Cpp#17]
您好，请问您能提供一下caffe版本的预测sample代码吗，我用您的mnet模型写出来的c++预测结果不太对。

**Comment by Charrin** [comment]
> 您好，请问您能提供一下caffe版本的预测sample代码吗，我用您的mnet模型写出来的c++预测结果不太对。

你只要用caffe的 c++ 接口替换一下inference就可以了
请你确认一下anchor解析是否正确

**Comment by yhl41001** [comment]
anchor解析用的是你里面的代码，我和mxnet的python对比了一下，看起来没问题。inference这部分我自己用caffe的写了，最后的参数拿出来和mxnet的对比了一下，不太一样。

**Comment by kk52099** [comment]
请问您这个问题解决了吗？ 我也是用caffe写了，结果比对非常不一样，检测不出人脸

**Comment by Charrin** [comment]
你可以发一下你调用的代码

**Comment by kk52099** [comment]
int w = cls->width();
    int h = cls->height(); 

	const float* reg_data = reg->cpu_data();
	const float* cls_data = cls->cpu_data()  ;
	const float* pts_data = pts->cpu_data();
    for (int i = 0; i < w; ++i) {
        for (int j = 0; j < h; ++j) {
            int id = j*w+i;
            for (int a = 0; a < anchor_num; ++a) {
               // if (cls->channels(0,anchor_num + a)[id] >= cls_threshold) {
			printf("cls %f\n", cls_data[id+ (a + anchor_num)*w*h]);
				if (cls_data[id + (a + anchor_num)*w*h] >= cls_threshold) {

帮我看一下获取cls_data这个数据的代码是否正确？谢谢

**Comment by Charrin** [comment]
> int w = cls->width();
> int h = cls->height();
> 
> ```
> const float* reg_data = reg->cpu_data();
> const float* cls_data = cls->cpu_data()  ;
> const float* pts_data = pts->cpu_data();
> for (int i = 0; i < w; ++i) {
>     for (int j = 0; j < h; ++j) {
>         int id = j*w+i;
>         for (int a = 0; a < anchor_num; ++a) {
>            // if (cls->channels(0,anchor_num + a)[id] >= cls_threshold) {
> 		printf("cls %f\n", cls_data[id+ (a + anchor_num)*w*h]);
> 			if (cls_data[id + (a + anchor_num)*w*h] >= cls_threshold) {
> ```
> 
> 帮我看一下获取cls_data这个数据的代码是否正确？谢谢

@kk52099 net input部分呢

**Comment by kk52099** [comment]
for (int i = 0; i < _feat_stride_fpn.size(); ++i) { 
		caffe::Blob<float> *cls;
		caffe::Blob<float> *reg;
		caffe::Blob<float> *pts;

        // get blob output
        char clsname[100]; sprintf(clsname, "face_rpn_cls_prob_reshape_stride%d", _feat_stride_fpn[i]);
        char regname[100]; sprintf(regname, "face_rpn_bbox_pred_stride%d", _feat_stride_fpn[i]);
        char ptsname[100]; sprintf(ptsname, "face_rpn_landmark_pred_stride%d", _feat_stride_fpn[i]);
		cls = net_->blob_by_name(clsname).get();
		reg = net_->blob_by_name(regname).get();
		pts = net_->blob_by_name(ptsname).get();

**Comment by kk52099** [comment]
boost::shared_ptr<Net<float> > net_; 
	net_.reset(new Net<float>("mnet.prototxt", TEST));

	net_->CopyTrainedLayersFrom("mnet.caffemodel");
Blob<float>* input_layer = net_->input_blobs()[0];
	int num_channels_ = input_layer->channels();
	Size input_geometry_ = Size(input_layer->width(), input_layer->height());

	//Blob<float>* input_layer = net_->input_blobs()[0];
	input_layer->Reshape(1, num_channels_, input_geometry_.height, input_geometry_.width);
	net_->Reshape();

int width = input_layer->width();
	int height = input_layer->height();
	float* input_data = input_layer->mutable_cpu_data();
	for (int i = 0; i < input_layer->channels(); ++i) {
		Mat channel(height, width, CV_32FC1, input_data);
		input_channels.push_back(channel);
		input_data += width * height;
	}

	Mat sample;
	if (img.channels() == 3 && num_channels_ == 1)
		cvtColor(img, sample, COLOR_BGR2GRAY);
	else if (img.channels() == 4 && num_channels_ == 1)
		cvtColor(img, sample, COLOR_BGRA2GRAY);
	else if (img.channels() == 4 && num_channels_ == 3)
		cvtColor(img, sample, COLOR_BGRA2BGR);
	else if (img.channels() == 1 && num_channels_ == 3)
		cvtColor(img, sample, COLOR_GRAY2BGR);
	else
		sample = img;

	Mat sample_resized;
	if (sample.size() != input_geometry_)
		resize(sample, sample_resized, input_geometry_);
	else
		sample_resized = sample;

	Mat image = sample_resized.clone();
	image.convertTo(image, CV_32FC3, 1.0 / 128, -127.5 / 128);
	split(image, input_channels);

	CHECK(reinterpret_cast<float*>(input_channels.at(0).data) == net_->input_blobs()[0]->cpu_data())
		<< "Input channels are not wrapping the input layer of the network. ";


	//Preprocess(img, &input_channels); //convert img to caffe input

	net_->Forward();


    std::vector<Anchor> proposals;
    proposals.clear();

    for (int i = 0; i < _feat_stride_fpn.size(); ++i) { 
		caffe::Blob<float> *cls;
		caffe::Blob<float> *reg;
		caffe::Blob<float> *pts;

        // get blob output
        char clsname[100]; sprintf(clsname, "face_rpn_cls_prob_reshape_stride%d", _feat_stride_fpn[i]);
        char regname[100]; sprintf(regname, "face_rpn_bbox_pred_stride%d", _feat_stride_fpn[i]);
        char ptsname[100]; sprintf(ptsname, "face_rpn_landmark_pred_stride%d", _feat_stride_fpn[i]);
		cls = net_->blob_by_name(clsname).get();
		reg = net_->blob_by_name(regname).get();
		pts = net_->blob_by_name(ptsname).get();
 ac[i].FilterAnchor(cls, reg, pts, proposals);

**Comment by kk52099** [comment]
值得一提的是，我加载prototxt文件时候出现错误，后来修改了crop的输入，才正确通过

**Comment by Charrin** [comment]
@kk52099 没看到你在哪把数据放进inputblob里
```
float* input_data = input_layer->mutable_cpu_data();
for (int i = 0; i < input_layer->channels(); ++i) {
Mat channel(height, width, CV_32FC1, input_data);
input_channels.push_back(channel);
input_data += width * height;
}

```
是这段吗？这段并没改变input data的数据

**Comment by kk52099** [comment]
这一段：Mat image = sample_resized.clone();
image.convertTo(image, CV_32FC3, 1.0 / 128, -127.5 / 128);
split(image, input_channels);

CHECK(reinterpret_cast<float*>(input_channels.at(0).data) == net_->input_blobs()[0]->cpu_data())
	<< "Input channels are not wrapping the input layer of the network. ";

**Comment by Charrin** [comment]
> 这一段：Mat image = sample_resized.clone();
> image.convertTo(image, CV_32FC3, 1.0 / 128, -127.5 / 128);
> split(image, input_channels);
> 
> CHECK(reinterpret_cast<float*>(input_channels.at(0).data) == net_->input_blobs()[0]->cpu_data())
> << "Input channels are not wrapping the input layer of the network. ";

@kk52099 不清楚opencv split内部会不会做内存的重新分配，可以把设置好之后把input blob重新读出来并显示看一下是否set成功？
另外请问一下加载prototxt出现了什么错误呢

**Comment by kk52099** [comment]
opencv split是没有问题的，我之前好多caffe模型也是这么输入的，另外我怀疑是我提取数据可能出错，您重点帮忙看一下，这句代码获取数据可信度值，if (cls_data[id + (a + anchor_num)*w*h] >= cls_threshold)是否正确？ 我感觉是问题出在这里cls_data[id + (a + anchor_num)*w*h]，  另外prototxt，layer {
  name: "crop1"
  type: "Crop"
  bottom: "rf_c1_red_conv_bn"
  bottom: "rf_c2_upsampling"
  
  top: "crop1"
}
crop层，bottom1与bottom2需要调整位置，不然caffe内部报错

**Comment by Charrin** [comment]
cls_data 这一段似乎并没有什么问题诶

**Comment by kk52099** [comment]
cls_data[id + (a + anchor_num)*w*h]；  cls_data中的 id + (a+anchor_num)*w*h 这个没有问题吗？ 还是应该是 id*anchor_num + anchor_num*w*h + a?   我总感觉是这边取得位置不对，但是这两种方式都出不来结果，因为这里获取的值大部分都是0.999x

**Comment by Charrin** [comment]
> cls_data[id + (a + anchor_num)_w_h]； cls_data中的 id + (a+anchor_num)_w_h 这个没有问题吗？ 还是应该是 id_anchor_num + anchor_num_w*h + a? 我总感觉是这边取得位置不对，但是这两种方式都出不来结果，因为这里获取的值大部分都是0.999x

cls输出的结果通道中0~anchor_num是neg得分，anchor_num~2* anchor_num是pos得分
0.999x说明这个anchor是正样本啊，为什么会没输出……

**Comment by Charrin** [comment]
> cls_data[id + (a + anchor_num)_w_h]； cls_data中的 id + (a+anchor_num)_w_h 这个没有问题吗？ 还是应该是 id_anchor_num + anchor_num_w*h + a? 我总感觉是这边取得位置不对，但是这两种方式都出不来结果，因为这里获取的值大部分都是0.999x

cls输出的结果通道中[0,anchor_num)是neg得分，[anchor_num,2* anchor_num)是pos得分
0.999x说明这个anchor是正样本啊，为什么会没输出……

**Comment by kk52099** [comment]
有输出，但是结果都不对，没有正确检测出人类位置，我也是找问题找了好久了，不知道您是否在caffe下跑过这个caffe模型，会不会是因为我修改了prototxt的原因，导致输出的数据就不对了，因为score的值都出现2435.738037或者14449.987305甚至更大的值，大部分是在0-1之间

**Comment by kk52099** [comment]
问题已经解决，谢谢您，讨论一番就开窍了，非常感谢

**Comment by PhenomenalOnee** [comment]
Can you please provide the code to run the c++ file detect.cpp with inference code

**Comment by deargqy** [comment]
> 问题已经解决，谢谢您，讨论一番就开窍了，非常感谢

hello~

想问下你最后怎么解决问题的呢~我crop也遇到了差不多的问题

**Comment by jackgao0323** [comment]
@Charrin @kk52099 可以请问一下input是normalize -1~1吗? 我现在使用TensorRT跟Caffe拿到一样的output，bbox没有出来，拿去跟Mxnet Output比较有点出入，我怀疑是不是input有问题。
`cv::Mat img = cv::imread("./test.jpg");

        cv::cvtColor(img, img, CV_BGR2RGB);
	
	cv::resize(img, img, cv::Size(INPUT_H, INPUT_W));

	cv::Mat frame_copy = img.clone();

	cv::resize(frame_copy, frame_copy, cv::Size(INPUT_W, INPUT_H));

	float* data = new float[INPUT_C*INPUT_H*INPUT_W];

	std::vector<cv::Mat> fd_input_channels;

	for (int i = 0; i < 3; ++i) {
		cv::Mat channel(INPUT_H, INPUT_W, CV_32FC1, data);
		fd_input_channels.push_back(channel);
		data += INPUT_H * INPUT_W;
	}

	cv::Mat sample_float;

	frame_copy.convertTo(sample_float, CV_32FC3, 1.0 / 128, -127.5 / 128);

	cv::split(sample_float, fd_input_channels);`

**Comment by Charrin** [comment]
不进行归一化

**Comment by jackgao0323** [comment]
问题已经解决了 非常感谢

**Comment by zheshipinyinMc** [comment]
> 问题已经解决，谢谢您，讨论一番就开窍了，非常感谢

@kk52099 @Charrin 同样遇到，检测框偏移很大的问题，请问可能是哪里出了问题呢？

**Comment by zheshipinyinMc** [comment]
框不对的问题解决了，实际上返回的box包含了左上角和右下角的坐标，但是将这两个坐标点保存在了Rect里面，即finabox.x和finalbox.y是左上角坐标，finalbox.weight和finalbox.height是右下角坐标。直接将finalbox传入opencv的retangle里面就会导致框偏移。
