### ISSUE TITLE
No "inference.hpp" header file

### ISSUE THREAD

**Issue by ForestWang** [Charrin/RetinaFace-Cpp#2]
there is no inference.hpp header file.

**Comment by Charrin** [comment]
> there is no inference.hpp header file.

you should replace your own inference framework there

**Comment by BrownOfSummer** [comment]
@Charrin Could you please release a complete version, maybe containing inference.hpp and inference_utils.hpp， thanks a lot !

**Comment by Charrin** [comment]
> @Charrin Could you please release a complete version, maybe containing inference.hpp and inference_utils.hpp， thanks a lot !

If you want to use Caffe, see Caffe c++ API to replace my inference.  The "class Inference" is "caffe::Net" and "class Cube" is "caffe::Blob"
It is not difficult if you are familiar with your inference framework.

**Comment by luan1412167** [comment]
@ForestWang did you solve it? Can you share class Cube? thanks
