### ISSUE TITLE
About the result test on WiderFace_val set for SINGLE SCALE

### ISSUE THREAD

**Issue by wanjinchang** [Charrin/RetinaFace-Cpp#20]
Good job! But I am confused about the result tested on wider face val set. Accord to this https://github.com/deepinsight/insightface/issues/669,  the result tested on WIDER Face Hard using mnet0.25 model is 0.791, and your readme showed is about 0.36. Could you tell me why the result has so big difference??

**Comment by Charrin** [comment]
i don’t use multi-scale test

**Comment by wanjinchang** [comment]
This deepinsight/insightface#669, the result on WIDER Face Hard using mnet0.25 model is 0.791 also testing on single scale...

**Comment by Charrin** [comment]
> This [deepinsight/insightface#669](https://github.com/deepinsight/insightface/issues/669), the result on WIDER Face Hard using mnet0.25 model is 0.791 also testing on single scale...

My target size is not as same as the result.
Because of my GPU memory limit, max size set to 1000, and I don't zoom in the image which max size < 1000
