### ISSUE TITLE
why resize to 300x300 before extraction

### ISSUE THREAD

**Issue by anguoyang** [Charrin/RetinaFace-Cpp#21]
hi @Charrin , 

	ncnn::Mat input = ncnn::Mat::from_pixels_resize(img.data, ncnn::Mat::PIXEL_BGR2RGB, img.cols, img.rows, 300, 300);
	cv::resize(img, img, cv::Size(300, 300));

300x300 is really small for bigger images, is it the network size? however, I found the param is 640:
Input            data             0 1 data 0=640 1=640 2=3

**Comment by Charrin** [comment]
You can change the input size

**Comment by anguoyang** [comment]
@Charrin thank you

**Comment by anguoyang** [comment]
btw, 
cv::rectangle (img, cv::Point((int)result[i].finalbox.x, (int)result[i].finalbox.y), cv::Point((int)result[i].finalbox.width, (int)result[i].finalbox.height), cv::Scalar(0, 255, 255), 2, 8, 0);

it seems that finalbox.width is actually width +x and finalbox.height is height +y, am I right? as in opencv cv::rectangle(img, point1, point2....), here point2 is the bottom right corner

**Comment by Charrin** [comment]
Yes, the format is x1y1x2y2, not xywh

**Comment by anguoyang** [comment]
I have tried with your demo, it was correct, but when I used my image, the proposals always got size=0, could you please tell me the possible reason? the same source code, but test.jpg changed.
I found that the faces in my image is big, while your faces are comparative small

**Comment by Charrin** [comment]
What’s the size of faces in your image? You can check whether the anchor size match your faces size, or resize the input image

**Comment by anguoyang** [comment]
sorry for the confusion, your original demo is OK even for my image.
I put your source code into my demo, refer to your source code in main function in detect.cpp.
I debugged into AnchorGenerator::FilterAnchor
.....................................
if (cls.channel(anchor_num + a)[id] >= cls_threshold) {
.................never go here.....................

**Comment by hanjw123** [comment]
same question！I found the max value of "cls.channel(anchor_num + a)[id] " is only 0.01, others are smaller. Have you solved this?

**Comment by anguoyang** [comment]
@hanjw123 no, but his demo code is OK, it is really strange

**Comment by anguoyang** [comment]
@Charrin @hanjw123 I found the problem and a type of solution:
save my opencv mat into a .jpg file(using imwrite), and use imread to load that jpg file, and use this new mat for 
ncnn::Mat input = ncnn::Mat::from_pixels_resize(new-img..............
then everything is ok.

but after testing with arcface, I found that the accuracy is not as good as with mtcnn, however the author said that retinaface will improve arcface, but my testing result is much worse

**Comment by Charrin** [comment]
@anguoyang thanks for your solution 
I think maybe the reasons of the accuracy problem are: 1. Mnet model is not official retina model, R50 is not the best official retina model and 2. You should train you model on the faces affine from retina landmarks, not from mtcnn landmarks

**Comment by anguoyang** [comment]
Thank you for your response. could you please tell me the related landmarks of retina face?
this is for mtcnn:
//Normal face landmark for 112x112,
float norm_face[5][2] = {
	{ 30.2946f + 8.0, 51.6963f },
	{ 65.5318f + 8.0, 51.5014f },
	{ 48.0252f + 8.0, 71.7366f },
	{ 33.5493f + 8.0, 92.3655f },
	{ 62.7299f + 8.0, 92.2041f } };

//Normal face landmark for 112x96,
float norm_face_2[5][2] = {
	{ 30.2946f , 51.6963f },
	{ 65.5318f, 51.5014f },
	{ 48.0252f, 71.7366f },
	{ 33.5493f, 92.3655f },
	{ 62.7299f, 92.2041f } };

**Comment by Charrin** [comment]
sorry, I can’t understand the “related landmarks” you said :(
These landmarks are same

**Comment by anguoyang** [comment]
sorry for the confusion:)
when we do affine with opencv(face alignment), we need the landmarks of normface, just as I described above, but it is for mtcnn, however, when we use retinaface, its probably different, so I need similar(but different) values for retinaface alignment

**Comment by Charrin** [comment]
> sorry for the confusion:)
> when we do affine with opencv(face alignment), we need the landmarks of normface, just as I described above, but it is for mtcnn, however, when we use retinaface, its probably different, so I need similar(but different) values for retinaface alignment

@anguoyang The landmarks meanings are the same, but maybe it has some little difference, especially between large pose. so I think you should re-detect the training data by retina model, and testing using retina model too.
