### ISSUE TITLE
error C2065: “anchor”: 未声明的标识符

### ISSUE THREAD

**Issue by youthM** [Charrin/RetinaFace-Cpp#23]
void AnchorGenerator::landmark_pred(const CRect2f anchor, const std::vector<cv::Point2f>& delta, std::vector<cv::Point2f>& pts) {
    float w = anchor[2] - anchor[0] + 1;
    float h = anchor[3] - anchor[1] + 1;
    float x_ctr = anchor[0] + 0.5 * (w - 1);
    float y_ctr = anchor[1] + 0.5 * (h - 1);
    pts.resize(delta.size());
    for (int i = 0; i < delta.size(); ++i) {
        	pts[i].x = (delta[i].x*w + x_ctr)*ratiow;
        	pts[i].y = (delta[i].y*h + y_ctr)*ratioh;
    }
}中出现该问题， @Charrin

**Comment by youthM** [comment]
@Charrin

**Comment by Charrin** [comment]
CRect 在anchor_generator头文件里定义 你检查一下编译的文件有没有问题吧

**Comment by youthM** [comment]
> CRect 在anchor_generator头文件里定义 你检查一下编译的文件有没有问题吧

class CRect2f {
    public:
	CRect2f(float x1, float y1, float x2, float y2) {
	    val[0] = x1;
	    val[1] = y1;
	    val[2] = x2;
	    val[3] = y2;
	}

	float& operator[](int i) {
	    return val[i];
	}

	float operator[](int i) const {
	    return val[i];
	}

	float val[4];

	void print() {
	    printf("rect %f %f %f %f\n", val[0], val[1], val[2], val[3]);
	}
};
跟你发布的一样，没有变化 @Charrin

**Comment by Charrin** [comment]
你能跑通ncnn的例子吗
