### ISSUE TITLE
Cube not defined

### ISSUE THREAD

**Issue by opentld** [Charrin/RetinaFace-Cpp#24]
int FilterAnchor(const Cube* cls, const Cube* reg, const Cube* pts, std::vector<Anchor>& result);

@Charrin   you must forget somthing...

**Comment by Charrin** [comment]
> int FilterAnchor(const Cube* cls, const Cube* reg, const Cube* pts, std::vector& result);
> 
> @Charrin you must forget somthing...

It depends on which framework you used. If you use Caffe, the cube is "caffe::Blob", if ncnn, the cube is "ncnn:Mat"
