### ISSUE TITLE
R50 mxnet convert to ncnn parameter file has inconsistent

### ISSUE THREAD

**Issue by wkj0121** [Charrin/RetinaFace-Cpp#25]
1、convert R50 use mxnet2ncnn then load model   
std::string param_path =  "./models/retina-R50.param";
    std::string bin_path = "./models/retina-R50.bin";
    ncnn::Net _net;
    _net.load_param(param_path.data());
    _net.load_model(bin_path.data());

2、when  run it error in  _extractor.extract(clsname, cls) error:load_model error at layer 282, parameter file has inconsistent 
 clsname	char [100]	"face_rpn_cls_prob_reshape_stride16"

**Comment by zZTaccount** [comment]
我也遇到了同样问题，请问您解决了吗？是怎么回事呢？
