### ISSUE TITLE
Got different output between Mxnet and caffe anything wrong?

### ISSUE THREAD

**Issue by jackgao0323** [Charrin/RetinaFace-Cpp#32]
I'm using mobilenet-0.25 Retinaface on TensorRT & caffe. They getting the same output value but no bbox output. Then I compare the output of caffe to Mxnet, it is different(Mxnet can get the bbox).
The preprocess is like below
`cv::Mat img = cv::imread("./test.jpg");

        cv::cvtColor(img, img, CV_BGR2RGB);
	
	cv::resize(img, img, cv::Size(INPUT_H, INPUT_W));

	cv::Mat frame_copy = img.clone();

	cv::resize(frame_copy, frame_copy, cv::Size(INPUT_W, INPUT_H));

	float* data = new float[INPUT_C*INPUT_H*INPUT_W];

	std::vector<cv::Mat> fd_input_channels;

	for (int i = 0; i < 3; ++i) {
		cv::Mat channel(INPUT_H, INPUT_W, CV_32FC1, data);
		fd_input_channels.push_back(channel);
		data += INPUT_H * INPUT_W;
	}

	cv::Mat sample_float;

	frame_copy.convertTo(sample_float, CV_32FC3, 1.0 / 128, -127.5 / 128);

	cv::split(sample_float, fd_input_channels);`

The input is normalize to -1~1 planar,right?

**Comment by xiakj** [comment]
我的输出结果跟官方比较也不一样，你解决了吗？

**Comment by jackgao0323** [comment]
@xiakejiang input不做归一化，结果就正确了。

**Comment by xiakj** [comment]
@jackgao0323 他那里面也并没有做归一化呀，连去均值都没有吧

**Comment by jackgao0323** [comment]
你说模型里面吗？ 好像没做

**Comment by xiakj** [comment]
@jackgao0323 对的，detect.cpp里面。你怎么搞一致的？

**Comment by xiakj** [comment]
@jackgao0323 如果不做任何修改，我跑出来的结果比官方的有较大损失。

**Comment by Charrin** [comment]
@xiakejiang 你的输入图片做过BGR-RGB的转换吗

**Comment by xiakj** [comment]
@jackgao0323 没有

**Comment by xiakj** [comment]
@jackgao0323 我还发现detect.cpp的resize方式和官方不一样

**Comment by Charrin** [comment]
@xiakejiang 输入要做通道的转换

**Comment by xiakj** [comment]
@jackgao0323 嗯嗯。忘记做通道转换了，效果确实提上来了。谢谢！

**Comment by xiakj** [comment]
@jackgao0323 其实官方也没有进行去均值归一化，可以看到retinaface.py中means = [0,0,0,] std = [1,1,1]

**Comment by jackgao0323** [comment]
@xiakejiang 后来去看才发现 官方没做归一化

**Comment by xiakj** [comment]
@jackgao0323 作者训练的时候是不也把归一化忘了，，，

**Comment by xiakj** [comment]
@Charrin 是这个原因，谢谢！

**Comment by xiakj** [comment]
@jackgao0323 我的输出结果跟官方比还是有较大差距，脸部检测框偏大，关键点偏离的也较远，什么原因呢？
