### ISSUE TITLE
How you convert mxnet to caffe model, Can you share your code?

### ISSUE THREAD

**Issue by LittleDonkey1203** [Charrin/RetinaFace-Cpp#9]

**Comment by Charrin** [comment]
I use MMDNN, add op support myself

**Comment by LittleDonkey1203** [comment]
Is caffe and mxnet model give you the same accuracy in Widerface dataset ?

**Comment by Charrin** [comment]
Please see README

**Comment by LittleDonkey1203** [comment]
Sorry, README only gives the difference of python and C++ version. Does the python version mean mxnet model accuracy, and C++ version mean caffe one?

**Comment by Charrin** [comment]
python version: origin mxnet model + origin retinaface.py
C++ version: converted caffe model + my cpp files

The net output of two models are the same. The wider results are saved in the “result fold”.

**Comment by LittleDonkey1203** [comment]
OK! Got it! Thank you very much!
